# Generated by Django 5.1.6 on 2025-03-28 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_on_cue', '0003_transcription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='midi_output',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='status',
        ),
        migrations.AddField(
            model_name='transcription',
            name='midi_file',
            field=models.FileField(default='', upload_to='transcriptions/midi/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcription',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(upload_to='transcriptions/audio/'),
        ),
        migrations.CreateModel(
            name='SheetMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_audio', models.FileField(upload_to='transcriptions/audio/')),
                ('midi_file', models.FileField(blank=True, null=True, upload_to='midi/')),
                ('musicxml', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
