# Generated by Django 5.1.6 on 2025-03-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_on_cue', '0004_alter_transcription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='midi_file',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/midi/'),
        ),
    ]
