# Generated by Django 5.1.6 on 2025-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_on_cue', '0005_alter_sheetmusic_midi_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmusic',
            name='midi_file',
            field=models.FileField(blank=True, null=True, upload_to='midi/'),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='musicxml',
            field=models.FileField(upload_to='musicxml/'),
        ),
        migrations.AlterField(
            model_name='sheetmusic',
            name='original_audio',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
