# Generated by Django 5.1.6 on 2025-03-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write_on_cue', '0006_alter_sheetmusic_midi_file_alter_sheetmusic_musicxml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetmusic',
            name='musicxml',
        ),
    ]
